Repository SSUMC-6th/Spring_Boot_B, pull requests merged in 2024-05, with the labels that each got.

#19 [니니] Chapter 4. DATABASE 설계 & AWS RDS 설정
  docs/.DS_Store
  docs/chapter4/.DS_Store
  docs/chapter4/keyword/.DS_Store
  docs/chapter4/keyword/Ch04keyword.md
  docs/chapter4/keyword/images/1_1.png
  docs/chapter4/keyword/images/2_1.png
  docs/chapter4/keyword/images/2_2.png
  docs/chapter4/keyword/images/3_1.png
  docs/chapter4/keyword/images/3_2.png
  docs/chapter4/keyword/images/4_1.png
  docs/chapter4/keyword/images/5_1.png
  docs/chapter4/keyword/images/6_1 .png
  docs/chapter4/mission/스크린샷 2024-05-07 오전 9.04.29.png
  docs/chapter4/practice/스크린샷 2024-05-06 오후 2.49.37.png
  docs/chapter4/practice/스크린샷 2024-05-06 오후 3.18.44.png
  docs/chapter4/practice/스크린샷 2024-05-06 오후 3.23.43.png
  docs/chapter4/practice/스크린샷 2024-05-06 오후 8.06.47.png
Labels: ✨ Chapter04

#18 [승수]Chapter 4. DATABASE 설계 & AWS RDS 설정 ✨ Chapter04
  docs/chapter4/ch_03keyword.md
Labels: ✨ Chapter04

#17 [Reli]Chapter 4. DATABASE 설계 & AWS RDS 설정
  .DS_Store
  chapter4/keyword/chapter4_keyword.md
  chapter4/mission/mission.png
  chapter4/pratice/pratice1.png
  chapter4/pratice/pratice2.png
  src/.DS_Store
Labels: ✨ Chapter04

#21 [레리] Chapter 5. 실전 SQL - 어떤 Query를 작성해야 할까?
  .DS_Store
  chpater5/mission/umc_5th.sql
  src/.DS_Store
Labels: ✨ Chapter05

#22 [nini] Chapter 5. 실전 SQL - 어떤 Query를 작성해야 할까?
  docs/.DS_Store
  docs/chapter5/.DS_Store
  docs/chapter5/mission/스크린샷 2024-05-14 오전 12.33.30.png
  docs/chapter5/mission/스크린샷 2024-05-14 오전 12.33.44.png
  docs/chapter5/mission/스크린샷 2024-05-14 오전 12.33.51.png
  docs/chapter5/mission/스크린샷 2024-05-14 오전 12.33.58.png
Labels: ✨ Chapter05

#23 [승수] Chapter 5. 실전 SQL - 어떤 Query를 작성해야 할까? ✨ Chapter05
  docs/chapter2/ch_02keyword.md
  docs/chapter3/ch_03keyword.md
  docs/chapter4/ch_03keyword.md
  src/mission/chapter3/Ch03mission
  src/mission/chapter5/sql
Labels: ✨ Chapter05

#24 Revert 23 seungsu/#5
  docs/chapter2/ch_02keyword.md
  docs/chapter3/ch_03keyword.md
  docs/chapter4/ch_03keyword.md
  src/mission/chapter3/Ch03mission
Labels: ✨ Chapter05

#27 [승수]Chapter 6. API URL의 설계 & 프로젝트 세팅 ✨ Chapter06
  src/mission/chapter6/REST-API
Labels: ✨ Chapter06

#28 [니니] Chapter 6. API URL의 설계 & 프로젝트 세팅
  docs/.DS_Store
  docs/chapter6/.DS_Store
  docs/chapter6/mission/.DS_Store
  docs/chapter6/mission/스크린샷 2024-05-21 오전 9.57.19.png
  docs/chapter6/mission/스크린샷 2024-05-21 오전 9.57.23.png
Labels: ✨ Chapter06

#25 [레리]Chapter 6. API URL의 설계 & 프로젝트 세팅
  .DS_Store
  chapter6/mission/mission.png
  chapter6/pratice/pratice1.png
  chapter6/pratice/pratice2.png
  src/.DS_Store
Labels: ✨ Chapter06

#31 [니니]Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  .DS_Store
  docs/.DS_Store
  docs/chapter7/.DS_Store
  docs/chapter7/keyword/.DS_Store
  docs/chapter7/keyword/Ch07keyword.md
  docs/chapter7/keyword/images/.DS_Store
  docs/chapter7/keyword/images/스크린샷 2024-05-28 오후 5.30.52.png
  docs/chapter7/mission/.DS_Store
  docs/chapter7/mission/스크린샷 2024-05-28 오후 4.56.53.png
  docs/chapter7/mission/스크린샷 2024-05-28 오후 5.06.11.png
  docs/chapter7/mission/스크린샷 2024-05-28 오후 5.07.12.png
  docs/chapter7/mission/스크린샷 2024-05-28 오후 5.22.04.png
Labels: ✨ Chapter07

#30 [레리]Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  .DS_Store
  chapter7/keyword/chapter7_keyword.md
  chapter7/mission/log.txt
  chapter7/mission/스크린샷 2024-05-28 오전 1.17.12.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.19.42.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.20.35.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.20.48.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.20.56.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.21.01.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.21.06.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.21.14.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.21.19.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.21.23.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.21.30.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.21.36.png
  chapter7/mission/스크린샷 2024-05-28 오전 1.21.42.png
Labels: ✨ Chapter07
