Repository SSUMC-6th/Spring_Boot_B, pull requests merged in 2024-06, with the labels that each got.

#39 [승수] Chapter 8. API 응답 통일 & 에러 핸들러
  docs/chapter8/ch_08keyword
  src/mission/chapter8/flag1.png
  src/mission/chapter8/flag2.png
  src/mission/chapter8/mission8
Labels: ✨ Chapter08

#36 [니니] Chapter 8. API 응답 통일 & 에러 핸들러
  docs/.DS_Store
  docs/chapter8/.DS_Store
  docs/chapter8/keyword/.DS_Store
  docs/chapter8/keyword/Ch08Keyword.md
  docs/chapter8/keyword/스크린샷 2024-06-03 오전 10.12.37.png
  docs/chapter8/mission/.DS_Store
  docs/chapter8/mission/mission8.pdf
  docs/chapter8/mission/nini/.gitignore
  docs/chapter8/mission/nini/build.gradle
  docs/chapter8/mission/nini/gradle/wrapper/gradle-wrapper.jar
  docs/chapter8/mission/nini/gradle/wrapper/gradle-wrapper.properties
  docs/chapter8/mission/nini/gradlew
  docs/chapter8/mission/nini/gradlew.bat
  docs/chapter8/mission/nini/settings.gradle
  docs/chapter8/mission/nini/src/main/java/umc/nini/NiniApplication.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/apiPayload/ApiResponse.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/apiPayload/code/BaseCode.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/apiPayload/code/BaseErrorCode.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/apiPayload/code/ErrorReasonDTO.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/apiPayload/code/ReasonDTO.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/apiPayload/code/status/ErrorStatus.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/apiPayload/code/status/SuccessStatus.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/controller/TempRestController.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/converter/TempConverter.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/FoodCategory.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/Member.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/MemberAgree.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/MemberMission.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/MemberPrefer.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/Mission.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/Region.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/Review.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/ReviewImage.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/Store.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/Terms.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/domain/common/BaseEntity.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/dto/TempRequest.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/dto/TempResponse.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/exception/ExceptionAdvice.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/exception/GeneralException.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/exception/handler/TempHandler.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/service/TempService/TempCommandService.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/service/TempService/TempCommandServiceImpl.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/service/TempService/TempQueryService.java
  docs/chapter8/mission/nini/src/main/java/umc/nini/service/TempService/TempQueryServiceImpl.java
  docs/chapter8/mission/nini/src/main/resources/application.yml
  docs/chapter8/mission/nini/src/test/java/umc/nini/NiniApplicationTests.java
Labels: ✨ Chapter08

#38 [승수]Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chpater7/ch_07keyword
  src/mission/chapter7/Untitled.png
  src/mission/chapter7/mission7
Labels: ✨ Chapter07

#37 [레리]Chapter 8. API 응답 통일 & 에러 핸들러
  chapter8/keyword.md
  chapter8/mission/스크린샷 2024-06-01 오후 3.49.50.png
  chapter8/mission/스크린샷 2024-06-02 오후 11.46.01.png
  chapter8/mission/스크린샷 2024-06-02 오후 11.46.09.png
  chapter8/mission/스크린샷 2024-06-03 오전 10.46.06.png
  chapter8/mission/스크린샷 2024-06-03 오전 11.06.15.png
  chapter8/mission/스크린샷 2024-06-03 오전 11.12.49.png
  chapter8/mission/스크린샷 2024-06-03 오전 11.45.49.png
Labels: ✨ Chapter08

#40 [레리]Chapter 9. API & Swagger & Annotation
  chapter9/keyword/ch.9 keyword.md
  chapter9/mission/스크린샷 2024-06-18 오후 1.44.44.png
  chapter9/mission/스크린샷 2024-06-18 오후 1.44.47.png
  chapter9/mission/스크린샷 2024-06-18 오후 1.45.02.png
  chapter9/mission/스크린샷 2024-06-18 오후 1.45.06.png
  chapter9/mission/스크린샷 2024-06-18 오후 1.45.19.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.01.48.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.01.50.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.02.15.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.02.17.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.03.19.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.04.02.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.04.37.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.05.13.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.05.15.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.07.19.png
  chapter9/mission/스크린샷 2024-06-18 오후 2.07.37.png
Labels: ✨ Chapter09

#41 [니니] Chapter 9. API & Swagger & Annotation
  .DS_Store
  docs/.DS_Store
  docs/chapter9/.DS_Store
  docs/chapter9/keyword/.DS_Store
  docs/chapter9/keyword/스크린샷 2024-06-18 오후 4.36.26.png
  docs/chapter9/keyword/스크린샷 2024-06-18 오후 4.36.36.png
  docs/chapter9/mission/nini_API.pdf
Labels: ✨ Chapter09

#42 [승수]Chapter 9. API & Swagger & Annotation
  docs/chapter9/ch_09Keyword
Labels: ✨ Chapter09

#44 [승수]Chapter 10. API & Paging
  docs/chapter10/ch_10Keyword
  src/mission/chapter10/1/Untitled (1).png
  src/mission/chapter10/1/Untitled (2).png
  src/mission/chapter10/1/Untitled (3).png
  src/mission/chapter10/1/Untitled (4).png
  src/mission/chapter10/1/Untitled (5).png
  src/mission/chapter10/1/Untitled (6).png
  src/mission/chapter10/1/Untitled.png
  src/mission/chapter10/2/Untitled (1).png
  src/mission/chapter10/2/Untitled (2).png
  src/mission/chapter10/2/Untitled (3).png
  src/mission/chapter10/2/Untitled (4).png
  src/mission/chapter10/2/Untitled.png
  src/mission/chapter10/3/Untitled (1).png
  src/mission/chapter10/3/Untitled (2).png
  src/mission/chapter10/3/Untitled (3).png
  src/mission/chapter10/3/Untitled (4).png
  src/mission/chapter10/3/Untitled.png
  src/mission/chapter10/mission10
Labels: ✨ Chapter10

#45 [니니]Chapter 10. API & Paging
  docs/.DS_Store
  docs/chapter10/.DS_Store
  docs/chapter10/keyword/.DS_Store
  docs/chapter10/keyword/Ch10Keyword.md
  docs/chapter10/mission/.DS_Store
  docs/chapter10/mission/Ch10Mission .pdf
Labels: ✨ Chapter10

#43 [레리]Chapter 10. API & Paging
  .DS_Store
  chapter10/keyword/chapter10.keyword.md
  chapter10/mission/스크린샷 2024-06-19 오전 11.47.53.png
  chapter10/mission/스크린샷 2024-06-19 오전 11.47.55.png
  chapter10/mission/스크린샷 2024-06-19 오전 11.48.54.png
  chapter10/mission/스크린샷 2024-06-19 오전 11.48.58.png
  chapter10/mission/스크린샷 2024-06-19 오전 11.49.50.png
  chapter10/mission/스크린샷 2024-06-19 오전 11.49.52.png
  chapter10/mission/스크린샷 2024-06-19 오전 11.50.44.png
  chapter10/mission/스크린샷 2024-06-19 오전 11.50.47.png
Labels: ✨ Chapter10
